apiVersion: v1
kind: Service
metadata:
  name: bertil
  namespace: bertil
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bertil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bertil
  namespace: bertil
spec:
  selector:
    matchLabels:
      app: bertil
  template:
    metadata:
      labels:
        app: bertil
    spec:
      containers:
        - name: bertil
          image: iteam1337/bertil
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "0.2Gi"
              cpu: "0.1"
            limits:
              cpu: "0.1"
              memory: "0.2Gi"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bertil-ingress
  namespace: bertil
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - bertil.iteam.services
      secretName: bertil-tls
  rules:
    - host: bertil.iteam.services
      http:
        paths:
          - path: /
            pathType: Prefix
            bertil:
              service:
                name: bertil
                port:
                  number: 80
