apiVersion: v1
kind: Service
metadata:
  name: bertil
  namespace: bertil
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: bertil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bertil
  namespace: bertil
spec:
  selector:
    matchLabels:
      app: bertil
  template:
    metadata:
      labels:
        app: bertil
    spec:
      containers:
        - name: bertil
          image: iteam1337/bertil
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "0.6Gi"
              cpu: "0.6"
            limits:
              memory: "0.6Gi"
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-bot-token
                  key: token
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: bertil-secret-key-base
                  key: secret-key-base

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bertil-ingress
  namespace: bertil
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - bertil.iteam.services
      secretName: bertil-tls
  rules:
    - host: bertil.iteam.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bertil
                port:
                  number: 4000
